name: quick_slideshow
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  flutter_animate: ^4.5.0
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_ffmpeg: ^0.4.2
  file_picker: ^8.0.3
  vector_math: ^2.1.4
  
  image_editor_plus: ^1.0.6
  screenshot: ^3.0.0
  permission_handler: ^11.1.0
  image: ^4.0.15
  extended_image: ^8.1.0
  hand_signature: ^3.0.0
  flex_color_picker: ^3.5.0
  colorfilter_generator: ^0.0.8
  font_awesome_flutter: ^10.7.0
  animated_widgets: ^1.1.0

  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  hive_generator: ^1.1.3
  build_runner: ^2.1.11


flutter:
  uses-material-design: true

  assets:
    - images/quick-slideshow-logo.png
